title : Form.io Help
kramdown:
  input: GFM
permalink: pretty
baseUrl: https://help.form.io
exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
collections:
  books:
    output: true
    permalink: /:path/
  chapters:
    output: false
  paragraphs:
    output: false
  sections:
    output: true
    permalink: /:path/
